/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thesystemone.GUI.DataLogin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import thesystemone.database.ConnectedDb;
import thesystemone.database.PerintahSQL;

/**
 *
 * @author dimas
 */
public class DataPengguna extends javax.swing.JInternalFrame {
	ConnectedDb driver;
	OperationPengguna opPengguna;
	private int n;
	private boolean simpanDataTambah;
	private boolean hapusData = true;

	/**
	 * Creates new form DataPengguna
	 */
	public DataPengguna() {
		initComponents();
		inisialisasi();
	}
	
	private void inisialisasi(){
		
		driver = new ConnectedDb();
		driver.panggilDriver();
		opPengguna = new OperationPengguna();
		kosongkanTabel();//mengosongkan baris pada table
		tampilToTabel(PerintahSQL.getPerintahSelect(PerintahSQL.tabelLogin));//menampilkan data yang ada di table login
		this.btnSave.setEnabled(false);//menonaktifkan button save
	}
	
	private DefaultTableModel getTabelModel(){
		return (DefaultTableModel) tabelPengguna.getModel();
	}

	public boolean isHapusData() {
		return hapusData;
	}

	public void setHapusData(boolean hapusData) {
		this.hapusData = hapusData;
	}
	
	private void aktifkanKomponen(boolean b){
		this.txtConfPass.setEnabled(b);
		this.txtUsername.setEnabled(b);
		this.txtPassword.setEnabled(b);
		this.cboHak.setEnabled(b);
	}
	
	private void aturKomponen(boolean tambah,boolean simpan,String batal){
		this.btnNew.setEnabled(tambah);
		this.btnEdit.setEnabled(tambah);
		this.btnSave.setEnabled(simpan);
		btnDelete.setText("Cancel");
		setHapusData(tambah);
		this.aktifkanKomponen(simpan);
	}
	
	private void dataDetail(int baris){
		this.txtUsername.setText(getTabelModel().getValueAt(baris, 0).toString());
		this.txtPassword.setText(getTabelModel().getValueAt(baris, 1).toString());
		this.txtConfPass.setText(getTabelModel().getValueAt(baris, 1).toString());
		this.cboHak.setSelectedIndex(Integer.valueOf(getTabelModel().getValueAt(baris, 2).toString()));
	}
	
	private int getJumlahDataTabel(){
		return getTabelModel().getRowCount()-1;
	}
	
	private boolean isSimpanTambah(){
		return simpanDataTambah;
	}
	
	private void kosongkanDataDetail(){
		this.txtUsername.setText("");
		this.txtPassword.setText("");
		this.txtConfPass.setText("");
		this.cboHak.setSelectedIndex(0);
	}
	
	private void kosongkanTabel(){
		int k = 0;
		while(k< getTabelModel().getRowCount()){
			getTabelModel().removeRow(0);
			k++;
		}
	}
	
	private void navigasiAkhir(){
		n = getTabelModel().getRowCount() - 1;
		int a = n;
		dataDetail(n);
		this.txtDataTerpilih.setText(Integer.toString(a+1));
	}
	
	private void navigasiAwal(){
		n = 0;
		int a= n;
		dataDetail(n);
		this.txtDataTerpilih.setText(Integer.toString(n+1));
	}
	
	private void navigasiMaju(){
		++n;
		if(n > getTabelModel().getRowCount()-1){
			n = getTabelModel().getRowCount()-1;
			JOptionPane.showMessageDialog(null, "Finnaly");
		}
		int a = n;
		dataDetail(a);
		this.txtDataTerpilih.setText(Integer.toString(a+1));
	}
	
	private void navigasiMundur(){
		--n;
		if(n < 0){
			n = 0;
			JOptionPane.showMessageDialog(null, "First");
		}
		int a = n;
		this.txtDataTerpilih.setText(Integer.toString(a+1));
		dataDetail(a);
	}
	
	private void addBarisKosong(){
		getTabelModel().addRow(new Object[]{null,null,null});
	}
	
	private void tampilToTabel(String sql){
		opPengguna.setDataTabel(sql);
		kosongkanTabel();
		for(int a = 0;a< opPengguna.getBanyakData();a++){
			addBarisKosong();
			for(int b = 0;b<getTabelModel().getColumnCount();b++){
				String[] data = opPengguna.getDataTabel(a);
				if(b==2){
					getTabelModel().setValueAt(Integer.parseInt(data[b]), a	, b);
				}else{
					getTabelModel().setValueAt(data[b], a, b);
				}
			}
		}
		this.txtJmlData.setText(this.getTabelModel().getRowCount()+"");
	}
	
	
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelPencarian = new javax.swing.JPanel();
                cekCari = new javax.swing.JCheckBox();
                lbFillter = new javax.swing.JLabel();
                cboPilih = new javax.swing.JComboBox();
                txtParam = new javax.swing.JTextField();
                btnCari = new javax.swing.JButton();
                scrolTabelPengguna = new javax.swing.JScrollPane();
                tabelPengguna = new javax.swing.JTable();
                panelDataTerpilih = new javax.swing.JPanel();
                lbUsername = new javax.swing.JLabel();
                lbPassword = new javax.swing.JLabel();
                lbConfPassword = new javax.swing.JLabel();
                lbHak = new javax.swing.JLabel();
                txtUsername = new javax.swing.JTextField();
                txtPassword = new javax.swing.JPasswordField();
                txtConfPass = new javax.swing.JPasswordField();
                cboHak = new javax.swing.JComboBox();
                panelTombol = new javax.swing.JPanel();
                btnExit = new javax.swing.JButton();
                btnClose = new javax.swing.JButton();
                btnNew = new javax.swing.JButton();
                btnEdit = new javax.swing.JButton();
                btnSave = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                panelNavigasi = new javax.swing.JPanel();
                btnAwal = new javax.swing.JButton();
                btnKembali = new javax.swing.JButton();
                btnAkhir = new javax.swing.JButton();
                btnMaju = new javax.swing.JButton();
                txtDataTerpilih = new javax.swing.JTextField();
                txtJmlData = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();

                setClosable(true);

                panelPencarian.setBorder(javax.swing.BorderFactory.createTitledBorder("Pencarian"));

                cekCari.setSelected(true);
                cekCari.setText("Show All");

                lbFillter.setText("Fillter By");

                cboPilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UserName", "HakAkses" }));
                cboPilih.setEnabled(false);

                txtParam.setEnabled(false);

                btnCari.setText("Cari");
                btnCari.setEnabled(false);

                javax.swing.GroupLayout panelPencarianLayout = new javax.swing.GroupLayout(panelPencarian);
                panelPencarian.setLayout(panelPencarianLayout);
                panelPencarianLayout.setHorizontalGroup(
                        panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPencarianLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cekCari)
                                .addGap(31, 31, 31)
                                .addComponent(lbFillter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtParam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btnCari)
                                .addContainerGap())
                );
                panelPencarianLayout.setVerticalGroup(
                        panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPencarianLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cekCari)
                                        .addComponent(lbFillter)
                                        .addComponent(cboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCari))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                tabelPengguna.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "UserName", "Password", "Access"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                scrolTabelPengguna.setViewportView(tabelPengguna);

                panelDataTerpilih.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Terpilih"));

                lbUsername.setText("Username");

                lbPassword.setText("Password");

                lbConfPassword.setText("Confirm Password");

                lbHak.setText("Hak Akses");

                txtUsername.setEnabled(false);
                txtUsername.addCaretListener(new javax.swing.event.CaretListener() {
                        public void caretUpdate(javax.swing.event.CaretEvent evt) {
                                txtUsernameCaretUpdate(evt);
                        }
                });

                txtPassword.setEnabled(false);
                txtPassword.addCaretListener(new javax.swing.event.CaretListener() {
                        public void caretUpdate(javax.swing.event.CaretEvent evt) {
                                txtPasswordCaretUpdate(evt);
                        }
                });

                txtConfPass.setEnabled(false);
                txtConfPass.addCaretListener(new javax.swing.event.CaretListener() {
                        public void caretUpdate(javax.swing.event.CaretEvent evt) {
                                txtConfPassCaretUpdate(evt);
                        }
                });

                cboHak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Operator" }));
                cboHak.setEnabled(false);

                javax.swing.GroupLayout panelDataTerpilihLayout = new javax.swing.GroupLayout(panelDataTerpilih);
                panelDataTerpilih.setLayout(panelDataTerpilihLayout);
                panelDataTerpilihLayout.setHorizontalGroup(
                        panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDataTerpilihLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(lbHak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUsername)
                                        .addComponent(cboHak, 0, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbConfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelDataTerpilihLayout.setVerticalGroup(
                        panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDataTerpilihLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbUsername)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbPassword)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDataTerpilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbConfPassword)
                                        .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbHak)
                                        .addComponent(cboHak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                panelTombol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

                btnExit.setText("Exit");
                btnExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExitActionPerformed(evt);
                        }
                });

                btnClose.setText("Close");
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCloseActionPerformed(evt);
                        }
                });

                btnNew.setText("NEW");
                btnNew.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNewActionPerformed(evt);
                        }
                });

                btnEdit.setText("EDIT");
                btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditActionPerformed(evt);
                        }
                });

                btnSave.setText("SAVE");
                btnSave.setEnabled(false);
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnDelete.setText("DELETE");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panelTombolLayout = new javax.swing.GroupLayout(panelTombol);
                panelTombol.setLayout(panelTombolLayout);
                panelTombolLayout.setHorizontalGroup(
                        panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTombolLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                panelTombolLayout.setVerticalGroup(
                        panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTombolLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnExit)
                                        .addComponent(btnClose)
                                        .addComponent(btnNew)
                                        .addComponent(btnEdit)
                                        .addComponent(btnSave)
                                        .addComponent(btnDelete))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                panelNavigasi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

                btnAwal.setText("Awal");
                btnAwal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAwalActionPerformed(evt);
                        }
                });

                btnKembali.setText("Kembali");
                btnKembali.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnKembaliActionPerformed(evt);
                        }
                });

                btnAkhir.setText("Akhir");
                btnAkhir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAkhirActionPerformed(evt);
                        }
                });

                btnMaju.setText("Maju");
                btnMaju.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMajuActionPerformed(evt);
                        }
                });

                txtDataTerpilih.setEditable(false);

                txtJmlData.setEditable(false);
                txtJmlData.addCaretListener(new javax.swing.event.CaretListener() {
                        public void caretUpdate(javax.swing.event.CaretEvent evt) {
                                txtJmlDataCaretUpdate(evt);
                        }
                });
                txtJmlData.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtJmlDataActionPerformed(evt);
                        }
                });

                jLabel1.setText("/");

                javax.swing.GroupLayout panelNavigasiLayout = new javax.swing.GroupLayout(panelNavigasi);
                panelNavigasi.setLayout(panelNavigasiLayout);
                panelNavigasiLayout.setHorizontalGroup(
                        panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNavigasiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDataTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJmlData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaju, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                panelNavigasiLayout.setVerticalGroup(
                        panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNavigasiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAwal)
                                        .addComponent(btnKembali)
                                        .addComponent(btnAkhir)
                                        .addComponent(btnMaju)
                                        .addComponent(txtDataTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtJmlData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(14, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelDataTerpilih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelPencarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrolTabelPengguna)
                                        .addComponent(panelTombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelNavigasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrolTabelPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelNavigasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDataTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTombol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwalActionPerformed
                // TODO add your handling code here:
		navigasiAwal();
        }//GEN-LAST:event_btnAwalActionPerformed

        private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
                // TODO add your handling code here:
		navigasiMundur();
        }//GEN-LAST:event_btnKembaliActionPerformed

        private void btnMajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajuActionPerformed
                // TODO add your handling code here:
		navigasiMaju();
        }//GEN-LAST:event_btnMajuActionPerformed

        private void btnAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkhirActionPerformed
                // TODO add your handling code here:
		navigasiAkhir();
        }//GEN-LAST:event_btnAkhirActionPerformed

        private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
                // TODO add your handling code here:
		simpanDataTambah = true;
		kosongkanDataDetail();
		aturKomponen(false, true, "Cancel");
		btnSave.setEnabled(false);
        }//GEN-LAST:event_btnNewActionPerformed

        private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
                // TODO add your handling code here:
		simpanDataTambah = false;
		aturKomponen(false, true, "Cancel");
		this.txtUsername.setEnabled(false);
        }//GEN-LAST:event_btnEditActionPerformed

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                // TODO add your handling code here:
		String us = txtUsername.getText();		
		int hak = cboHak.getSelectedIndex();
		if(isSimpanTambah()){
			opPengguna.simpanData(us, getPass2(), hak);
			tampilToTabel(PerintahSQL.getPerintahSelect(PerintahSQL.tabelLogin));
			dataDetail(getJumlahDataTabel() -1);
		}else{
			opPengguna.ubahData(us, getPass2(), hak);
			simpanDataTambah = true;
			tampilToTabel(PerintahSQL.getPerintahSelect(PerintahSQL.tabelLogin));
			dataDetail(0);
		}
		aturKomponen(true, false, "Delete");
        }//GEN-LAST:event_btnSaveActionPerformed

        private void txtConfPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConfPassCaretUpdate
                // TODO add your handling code here:
		if(getPass1().equals("")||getPass2().equals("")){
			btnSave.setEnabled(false);
		}else if(getPass2().equals(getPass1())||getPass1().equals(getPass2())){
			btnSave.setEnabled(true);
		}else{
			btnSave.setEnabled(false);
		}
        }//GEN-LAST:event_txtConfPassCaretUpdate

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                // TODO add your handling code here:
		if(isHapusData()){
			opPengguna.hapusData(this.txtUsername.getText());
			tampilToTabel(PerintahSQL.getPerintahSelect(PerintahSQL.tabelLogin));
			dataDetail(0);
		}else{
			aturKomponen(true, false, "Delete");
		}
        }//GEN-LAST:event_btnDeleteActionPerformed

        private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
                // TODO add your handling code here:
		this.dispose();
        }//GEN-LAST:event_btnCloseActionPerformed

        private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
                // TODO add your handling code here:
		System.exit(0);
        }//GEN-LAST:event_btnExitActionPerformed

        private void txtJmlDataCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtJmlDataCaretUpdate
                // TODO add your handling code here:
        }//GEN-LAST:event_txtJmlDataCaretUpdate

        private void txtPasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPasswordCaretUpdate
                // TODO add your handling code here:
		if(getPass1().equals("")){
			btnSave.setEnabled(false);
		}
        }//GEN-LAST:event_txtPasswordCaretUpdate

        private void txtUsernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtUsernameCaretUpdate
                // TODO add your handling code here:
		if(txtUsername.getText().equals("")){
			btnSave.setEnabled(false);
		}
        }//GEN-LAST:event_txtUsernameCaretUpdate

        private void txtJmlDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlDataActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txtJmlDataActionPerformed

	private String getPass1(){
		char[] a = txtPassword.getPassword();
		return String.valueOf(a);		
	}
	
	private String getPass2(){
		char[] b = txtConfPass.getPassword();
		return String.valueOf(b);
	}
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAkhir;
        private javax.swing.JButton btnAwal;
        private javax.swing.JButton btnCari;
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnExit;
        private javax.swing.JButton btnKembali;
        private javax.swing.JButton btnMaju;
        private javax.swing.JButton btnNew;
        private javax.swing.JButton btnSave;
        private javax.swing.JComboBox cboHak;
        private javax.swing.JComboBox cboPilih;
        private javax.swing.JCheckBox cekCari;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel lbConfPassword;
        private javax.swing.JLabel lbFillter;
        private javax.swing.JLabel lbHak;
        private javax.swing.JLabel lbPassword;
        private javax.swing.JLabel lbUsername;
        private javax.swing.JPanel panelDataTerpilih;
        private javax.swing.JPanel panelNavigasi;
        private javax.swing.JPanel panelPencarian;
        private javax.swing.JPanel panelTombol;
        private javax.swing.JScrollPane scrolTabelPengguna;
        private javax.swing.JTable tabelPengguna;
        private javax.swing.JPasswordField txtConfPass;
        private javax.swing.JTextField txtDataTerpilih;
        private javax.swing.JTextField txtJmlData;
        private javax.swing.JTextField txtParam;
        private javax.swing.JPasswordField txtPassword;
        private javax.swing.JTextField txtUsername;
        // End of variables declaration//GEN-END:variables
}
