/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package thesystemone.GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import thesystemone.GUI.DataLogin.DataPengguna;
import thesystemone.GUI.Login.GuiLogin;
import thesystemone.GUI.pelanggan.Pelanggan;
import thesystemone.GUI.product.Product;

/**
 *
 * @author dimas
 */
public class MainMenu extends javax.swing.JFrame {
	GuiLogin login;
	private boolean pemakaiAktif;
	/**
	 * Creates new form MainMenu
	 */
	public MainMenu() {
		initComponents();
		panggilJendelaLogin();
		setMenuBarEnabled(login.opLogin.isLogin(), login.opLogin.isAdmin());
	}

	public boolean isPemakaiAktif() {
		return pemakaiAktif;
	}

	public void setPemakaiAktif(boolean pemakaiAktif) {
		this.mniLogout.setEnabled(pemakaiAktif);
		this.mniLogin.setEnabled(!pemakaiAktif);
		this.pemakaiAktif = pemakaiAktif;
	}
	
	
	
	public void jendelaDalam(JInternalFrame frame){
		frame.setVisible(true);
		frame.setResizable(true);
		desktop.add(frame);
		this.setContentPane(desktop);
	}
	
	public void panggilJendelaLogin(){
		login = new GuiLogin(this, true);
		//menampilkan jendala login ditengah layar
		Dimension lebar = Toolkit.getDefaultToolkit().getScreenSize();
		int l = (lebar.width - login.getSize().width/2);
		int t = (lebar.height - login.getSize().height/2);
		login.setLocation(l, t);
		login.setVisible(true);
	}
	
	private void setMenuBarEnabled(boolean mnu,boolean mni){
		mnuInput.setEnabled(mnu);
		mnuTransaksi.setEnabled(false);
		mniPakai.setEnabled(mni);
		setPemakaiAktif(mnu);		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                desktop = new javax.swing.JDesktopPane();
                mnuBar = new javax.swing.JMenuBar();
                mnuFile = new javax.swing.JMenu();
                mniLogin = new javax.swing.JMenuItem();
                mniLogout = new javax.swing.JMenuItem();
                jSeparator1 = new javax.swing.JPopupMenu.Separator();
                mniExit = new javax.swing.JMenuItem();
                mnuInput = new javax.swing.JMenu();
                mniProduct = new javax.swing.JMenuItem();
                mniDataPelanggan = new javax.swing.JMenuItem();
                mniPakai = new javax.swing.JMenuItem();
                mnuTransaksi = new javax.swing.JMenu();
                mniJual = new javax.swing.JMenuItem();
                mnuHelp = new javax.swing.JMenu();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Seller Application");

                javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
                desktop.setLayout(desktopLayout);
                desktopLayout.setHorizontalGroup(
                        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                desktopLayout.setVerticalGroup(
                        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 279, Short.MAX_VALUE)
                );

                getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

                mnuFile.setText("File");

                mniLogin.setText("Login");
                mniLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniLoginActionPerformed(evt);
                        }
                });
                mnuFile.add(mniLogin);

                mniLogout.setText("Logout");
                mniLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniLogoutActionPerformed(evt);
                        }
                });
                mnuFile.add(mniLogout);
                mnuFile.add(jSeparator1);

                mniExit.setText("Exit");
                mniExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniExitActionPerformed(evt);
                        }
                });
                mnuFile.add(mniExit);

                mnuBar.add(mnuFile);

                mnuInput.setText("Input");

                mniProduct.setText("Data Product");
                mniProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniProductActionPerformed(evt);
                        }
                });
                mnuInput.add(mniProduct);

                mniDataPelanggan.setText("Data Pelanggan");
                mniDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniDataPelangganActionPerformed(evt);
                        }
                });
                mnuInput.add(mniDataPelanggan);

                mniPakai.setText("Data Pemakai");
                mniPakai.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniPakaiActionPerformed(evt);
                        }
                });
                mnuInput.add(mniPakai);

                mnuBar.add(mnuInput);

                mnuTransaksi.setText("Transaction");

                mniJual.setText("Penjualan");
                mniJual.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniJualActionPerformed(evt);
                        }
                });
                mnuTransaksi.add(mniJual);

                mnuBar.add(mnuTransaksi);

                mnuHelp.setText("Help");
                mnuBar.add(mnuHelp);

                setJMenuBar(mnuBar);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
                // TODO add your handling code here:
		this.dispose();
        }//GEN-LAST:event_mniExitActionPerformed

        private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
                // TODO add your handling code here:
		desktop.removeAll();
		desktop.repaint();
		panggilJendelaLogin();
		setMenuBarEnabled(login.opLogin.isLogin(), login.opLogin.isAdmin());
        }//GEN-LAST:event_mniLoginActionPerformed

        private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
                // TODO add your handling code here:
		desktop.removeAll();
		desktop.repaint();
		setMenuBarEnabled(false, false);
		panggilJendelaLogin();
		setMenuBarEnabled(login.opLogin.isLogin(), login.opLogin.isAdmin());
        }//GEN-LAST:event_mniLogoutActionPerformed

        private void mniProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProductActionPerformed
                // TODO add your handling code here:
		jendelaDalam(new Product());
        }//GEN-LAST:event_mniProductActionPerformed

        private void mniPakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPakaiActionPerformed
                // TODO add your handling code here:
		jendelaDalam(new DataPengguna());
        }//GEN-LAST:event_mniPakaiActionPerformed

        private void mniJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniJualActionPerformed
                // TODO add your handling code here:
		//jendelaDalam(new Penjualan());
        }//GEN-LAST:event_mniJualActionPerformed

        private void mniDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDataPelangganActionPerformed
                // TODO add your handling code here:
		jendelaDalam(new Pelanggan());
        }//GEN-LAST:event_mniDataPelangganActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainMenu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JDesktopPane desktop;
        private javax.swing.JPopupMenu.Separator jSeparator1;
        private javax.swing.JMenuItem mniDataPelanggan;
        private javax.swing.JMenuItem mniExit;
        private javax.swing.JMenuItem mniJual;
        private javax.swing.JMenuItem mniLogin;
        private javax.swing.JMenuItem mniLogout;
        private javax.swing.JMenuItem mniPakai;
        private javax.swing.JMenuItem mniProduct;
        private javax.swing.JMenuBar mnuBar;
        private javax.swing.JMenu mnuFile;
        private javax.swing.JMenu mnuHelp;
        private javax.swing.JMenu mnuInput;
        private javax.swing.JMenu mnuTransaksi;
        // End of variables declaration//GEN-END:variables
}
